# FIFA World Cup 2026 — Objective 1, Task 3
## Raw Population → Final Sample

### Purpose
This notebook only shows how the final 36-team sample is created from the 48-team raw population.

It does **not** perform the main Task 3 statistical analysis.

Process:

1. Load the raw 48-team population
2. Calculate Shooting Accuracy
3. Split teams into Advanced and Eliminated groups
4. Apply 75% proportionate stratified random sampling
5. Show the 36 selected teams
6. Show the 12 teams not selected

## 1. Load the raw population

In [1]:
import pandas as pd

raw = pd.read_csv("Task3_Raw_Population.csv")

print("Raw population rows:", len(raw))
print("\nOutcome counts:")
print(raw["Outcome"].value_counts())

raw.head()

Raw population rows: 48

Outcome counts:
Outcome
Advanced      32
Eliminated    16
Name: count, dtype: int64

  Group  ...                                         Source_URL
0     A  ...  https://fbref.com/en/squads/2740937c/2026/matc...
1     A  ...  https://fbref.com/en/squads/473f0fbf/2026/matc...
2     A  ...  https://fbref.com/en/squads/b009a548/2026/matc...
3     A  ...  https://fbref.com/en/squads/506f1741/2026/matc...
4     B  ...  https://fbref.com/en/squads/6c5ef1c3/2026/matc...

[5 rows x 6 columns]

## 2. Calculate Shooting Accuracy

The website data gives:
- Total Shots
- Shots on Target

Python calculates:

**Shooting Accuracy (%) = (Shots on Target / Total Shots) × 100**

In [2]:
population = raw.copy()

population["Shooting_Accuracy"] = (
    population["Shots_on_Target"] / population["Total_Shots"] * 100
)

population[
    ["Group", "Team", "Outcome", "Total_Shots",
     "Shots_on_Target", "Shooting_Accuracy"]
].head(10)

  Group                    Team  ... Shots_on_Target  Shooting_Accuracy
0     A                 Czechia  ...               8          23.529412
1     A          Korea Republic  ...              11          34.375000
2     A                  Mexico  ...              13          37.142857
3     A            South Africa  ...              10          30.303030
4     B  Bosnia and Herzegovina  ...              11          40.740741
5     B                  Canada  ...              21          36.206897
6     B                   Qatar  ...               7          38.888889
7     B             Switzerland  ...              18          40.000000
8     C                  Brazil  ...              19          46.341463
9     C                   Haiti  ...               7          22.580645

[10 rows x 6 columns]

## 3. Split the population into Advanced and Eliminated teams

Population:
- 32 Advanced teams
- 16 Eliminated teams

In [3]:
advanced_population = population[
    population["Outcome"] == "Advanced"
]

eliminated_population = population[
    population["Outcome"] == "Eliminated"
]

print("Advanced population:", len(advanced_population))
print("Eliminated population:", len(eliminated_population))

Advanced population: 32
Eliminated population: 16

## 4. Create the final 36-team sample

We select 75% from each group:

- 24 of 32 Advanced teams
- 12 of 16 Eliminated teams

`random_state=42` is fixed so the same teams are selected every time the notebook is run.

In [4]:
advanced_sample = advanced_population.sample(
    n=24,
    random_state=42
)

eliminated_sample = eliminated_population.sample(
    n=12,
    random_state=42
)

sample = pd.concat(
    [advanced_sample, eliminated_sample],
    ignore_index=True
)

print("Final sample size:", len(sample))
print("\nSample outcome counts:")
print(sample["Outcome"].value_counts())

Final sample size: 36

Sample outcome counts:
Outcome
Advanced      24
Eliminated    12
Name: count, dtype: int64

## 5. Final 36 selected teams

In [5]:
sample[
    ["Group", "Team", "Outcome", "Total_Shots",
     "Shots_on_Target", "Shooting_Accuracy"]
].sort_values(["Outcome", "Group", "Team"])

   Group                    Team  ... Shots_on_Target  Shooting_Accuracy
9      A                  Mexico  ...              13          37.142857
16     A            South Africa  ...              10          30.303030
17     B  Bosnia and Herzegovina  ...              11          40.740741
19     B                  Canada  ...              21          36.206897
10     B             Switzerland  ...              18          40.000000
12     C                  Brazil  ...              19          46.341463
4      D                Paraguay  ...               5          21.739130
5      D                     USA  ...              15          34.090909
14     E                 Ecuador  ...              19          41.304348
8      E                 Germany  ...              22          41.509434
13     F                   Japan  ...              11          47.826087
1      F                  Sweden  ...              20          50.000000
11     G                 Belgium  ...              20          27.397260
3      G                   Egypt  ...              13          27.083333
23     H              Cape Verde  ...               7          21.212121
20     I                  Norway  ...              16          45.714286
22     I                 Senegal  ...              18          36.000000
15     J                 Algeria  ...              13          36.111111
2      J               Argentina  ...              15          44.117647
7      J                 Austria  ...               8          29.629630
18     K                Colombia  ...              19          32.203390
21     K                Congo DR  ...               7          20.588235
0      L                 Croatia  ...              11          45.833333
6      L                 England  ...              20          34.482759
24     A                 Czechia  ...               8          23.529412
25     A          Korea Republic  ...              11          34.375000
32     B                   Qatar  ...               7          38.888889
34     C                Scotland  ...               7          24.137931
26     D                 Türkiye  ...              16          22.535211
35     F                 Tunisia  ...               6          33.333333
30     G                    Iran  ...              11          29.729730
31     G             New Zealand  ...              15          48.387097
29     H                 Uruguay  ...              13          26.530612
28     J                  Jordan  ...               9          37.500000
27     K              Uzbekistan  ...               5          27.777778
33     L                  Panama  ...               7          21.875000

[36 rows x 6 columns]

## 6. 12 teams not selected

These teams are **not bad data**.

They are simply the 12 teams that were not selected by the 75% proportionate stratified random sampling process.

In [6]:
excluded = population[
    ~population["Team"].isin(sample["Team"])
].copy()

excluded["Reason"] = (
    "Not selected by the 75% proportionate stratified random sample "
    "(random_state=42)."
)

print("Teams not selected:", len(excluded))

excluded[
    ["Group", "Team", "Outcome", "Shooting_Accuracy", "Reason"]
].sort_values(["Outcome", "Group", "Team"])

Teams not selected: 12

   Group  ...                                             Reason
10     C  ...  Not selected by the 75% proportionate stratifi...
12     D  ...  Not selected by the 75% proportionate stratifi...
17     E  ...  Not selected by the 75% proportionate stratifi...
21     F  ...  Not selected by the 75% proportionate stratifi...
30     H  ...  Not selected by the 75% proportionate stratifi...
32     I  ...  Not selected by the 75% proportionate stratifi...
42     K  ...  Not selected by the 75% proportionate stratifi...
46     L  ...  Not selected by the 75% proportionate stratifi...
9      C  ...  Not selected by the 75% proportionate stratifi...
16     E  ...  Not selected by the 75% proportionate stratifi...
29     H  ...  Not selected by the 75% proportionate stratifi...
33     I  ...  Not selected by the 75% proportionate stratifi...

[12 rows x 5 columns]

## Final result

The bridge step is complete:

**48-team raw population → Shooting Accuracy calculated → 36-team final sample**

The main Task 3 notebook can now use this 36-team sample for the actual statistical analysis.